### PR TITLE
Added new overload for SparseMatrixAssembler

### PR DESCRIPTION
**Pull request by amartinhuertas**
Added new overload for SparseMatrixAssembler to let one select the local matrix and vector types

### CODE REVIEW

**Comment by amartinhuertas** [comment]
For the records ... nonlinear solver test is failing with SparseMatrixCSR as local storage format of PSparseMatrix

```
(base) amartin@sistemas-ThinkPad-X1-Carbon-6th:~/git-repos/GridapDistributed.jl$ julia --project=. test/sequential/PLaplacianTests.jl 
ERROR: LoadError: setindex! not defined for SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}
Stacktrace:
  [1] error(::String, ::Type)
    @ Base ./error.jl:42
  [2] error_if_canonical_setindex(::IndexCartesian, ::SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, ::Int64, ::Int64)
    @ Base ./abstractarray.jl:1277
  [3] setindex!
    @ ./abstractarray.jl:1266 [inlined]
  [4] _setindex!
    @ ./abstractarray.jl:1297 [inlined]
  [5] setindex!
    @ ./abstractarray.jl:1267 [inlined]
  [6] setindex!(::PartitionedArrays.LocalView{Float64, 2, SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, Tuple{Vector{Int32}, Vector{Int32}}}, ::Float64, ::Int64, ::Int64)
    @ PartitionedArrays ~/.julia/packages/PartitionedArrays/0zLYD/src/Interfaces.jl:1861
  [7] add_entry!
    @ ~/.julia/packages/Gridap/3bh1p/src/Algebra/AlgebraInterfaces.jl:92 [inlined]
  [8] _add_entries!
    @ ~/.julia/packages/Gridap/3bh1p/src/Algebra/AlgebraInterfaces.jl:149 [inlined]
  [9] add_entries!
    @ ~/.julia/packages/Gridap/3bh1p/src/Algebra/AlgebraInterfaces.jl:127 [inlined]
 [10] evaluate!(cache::Nothing, k::Gridap.Arrays.AddEntriesMap{typeof(+)}, A::PartitionedArrays.LocalView{Float64, 2, SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, Tuple{Vector{Int32}, Vector{Int32}}}, v::Matrix{Float64}, i::Vector{Int64}, j::Vector{Int64})
    @ Gridap.Arrays ~/.julia/packages/Gridap/3bh1p/src/Arrays/AlgebraMaps.jl:47
 [11] _numeric_loop_matvec!(A::PartitionedArrays.LocalView{Float64, 2, SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, Tuple{Vector{Int32}, Vector{Int32}}}, b::PartitionedArrays.LocalView{Float64, 1, Vector{Float64}, Tuple{Vector{Int32}}}, caches::Tuple{Nothing, Nothing, Tuple{Tuple{Nothing, Nothing, Tuple{Tuple{Tuple{Nothing, Tuple{Gridap.Arrays.CachedMatrix{Float64, Matrix{Float64}}, Gridap.Arrays.CachedVector{Float64, Vector{Float64}}}, Tuple{Tuple{Tuple{Nothing, Gridap.Arrays.CachedArray{Float64, 3, Array{Float64, 3}}, Tuple{Nothing, Tuple{Tuple{Nothing, Gridap.Arrays.CachedArray{Gridap.TensorValues.VectorValue{2, Float64}, 3, Array{Gridap.TensorValues.VectorValue{2, Float64}, 3}}, Tuple{Nothing, Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Gridap.TensorValues.VectorValue{2, Float64}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}, Tuple{Nothing, Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Gridap.TensorValues.VectorValue{2, Float64}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}, Tuple{Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Float64, Vector{Float64}}, Tuple{Gridap.Arrays.CachedVector{Int32, Vector{Int32}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Float64}}}, Nothing}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}}}}, Gridap.Arrays.IndexItemPair{Int64, Array{Gridap.TensorValues.VectorValue{2, Float64}, 3}}}}}, Gridap.Arrays.IndexItemPair{Int64, Array{Float64, 3}}}, Nothing, Nothing}}, Gridap.Arrays.IndexItemPair{Int64, Matrix{Float64}}}, Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Float64, Vector{Float64}}, Tuple{Tuple{Tuple{Nothing, Gridap.Arrays.CachedMatrix{Float64, Matrix{Float64}}, Tuple{Tuple{Tuple{Nothing, Gridap.Arrays.CachedMatrix{Float64, Matrix{Float64}}, Tuple{Nothing, Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Gridap.TensorValues.VectorValue{2, Float64}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}, Tuple{Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Gridap.TensorValues.VectorValue{2, Float64}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}, Tuple{Nothing, Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Gridap.TensorValues.VectorValue{2, Float64}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}, Tuple{Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Float64, Vector{Float64}}, Tuple{Gridap.Arrays.CachedVector{Int32, Vector{Int32}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Float64}}}, Nothing}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}}}}, Gridap.Arrays.IndexItemPair{Int64, Matrix{Float64}}}, Tuple{Tuple{Nothing, Gridap.Arrays.CachedMatrix{Float64, Matrix{Float64}}, Tuple{Nothing, Tuple{Tuple{Nothing, Tuple{Gridap.Arrays.CachedVector{Float64, Vector{Float64}}, Nothing}, Tuple{Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Gridap.TensorValues.VectorValue{2, Float64}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}, Tuple{Nothing}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Gridap.TensorValues.VectorValue{2, Float64}}}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Float64}}}}}, Gridap.Arrays.IndexItemPair{Int64, Matrix{Float64}}}}}, Gridap.Arrays.IndexItemPair{Int64, Matrix{Float64}}}, Nothing, Nothing}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Float64}}}}}, Gridap.Arrays.IndexItemPair{Int64, Tuple{Matrix{Float64}, Vector{Float64}}}}, Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Int64, Vector{Int64}}, Tuple{Gridap.Arrays.CachedVector{Int32, Vector{Int32}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Int64}}}, Tuple{Tuple{Nothing, Gridap.Arrays.CachedVector{Int64, Vector{Int64}}, Tuple{Gridap.Arrays.CachedVector{Int32, Vector{Int32}}}}, Gridap.Arrays.IndexItemPair{Int64, Vector{Int64}}}}, cell_vals::Gridap.Arrays.LazyArray{FillArrays.Fill{typeof(tuple), 1, Tuple{Base.OneTo{Int64}}}, Tuple{Matrix{Float64}, Vector{Float64}}, 1, Tuple{Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.IntegrationMap, 1, Tuple{Base.OneTo{Int64}}}, Matrix{Float64}, 1, Tuple{Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{typeof(LinearAlgebra.dot)}, 1, Tuple{Base.OneTo{Int64}}}, Array{Float64, 3}, 1, Tuple{FillArrays.Fill{Matrix{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{Main.PLaplacianTestsSeq.PLaplacianTests.var"#dσ#4"}, 1, Tuple{Base.OneTo{Int64}}}, Array{Gridap.TensorValues.VectorValue{2, Float64}, 3}, 1, Tuple{FillArrays.Fill{Gridap.Fields.TransposeFieldIndices{Matrix{Gridap.TensorValues.VectorValue{2, Float64}}, Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{typeof(LinearAlgebra.dot)}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{FillArrays.Fill{Vector{Gridap.TensorValues.TensorValue{2, 2, Float64, 4}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.LinearCombinationMap{Colon}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Arrays.Broadcasting{Gridap.Arrays.PosNegReindex{Vector{Float64}, Vector{Float64}}}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Float64}, 1, Tuple{Gridap.Arrays.Table{Int32, Vector{Int32}, Vector{Int32}}}}, FillArrays.Fill{Matrix{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Base.OneTo{Int64}}}}}}}}}}}, FillArrays.Fill{Vector{Float64}, 1, Tuple{Base.OneTo{Int64}}}, FillArrays.Fill{Vector{Gridap.TensorValues.TensorValue{2, 2, Float64, 4}}, 1, Tuple{Base.OneTo{Int64}}}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.IntegrationMap, 1, Tuple{Base.OneTo{Int64}}}, Vector{Float64}, 1, Tuple{Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{typeof(-)}, 1, Tuple{Base.OneTo{Int64}}}, Matrix{Float64}, 1, Tuple{Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{typeof(LinearAlgebra.dot)}, 1, Tuple{Base.OneTo{Int64}}}, Matrix{Float64}, 1, Tuple{FillArrays.Fill{Matrix{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{Main.PLaplacianTestsSeq.PLaplacianTests.var"#σ#3"}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{typeof(LinearAlgebra.dot)}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{FillArrays.Fill{Vector{Gridap.TensorValues.TensorValue{2, 2, Float64, 4}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.LinearCombinationMap{Colon}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Arrays.Broadcasting{Gridap.Arrays.PosNegReindex{Vector{Float64}, Vector{Float64}}}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Float64}, 1, Tuple{Gridap.Arrays.Table{Int32, Vector{Int32}, Vector{Int32}}}}, FillArrays.Fill{Matrix{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Base.OneTo{Int64}}}}}}}}}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.BroadcastingFieldOpMap{typeof(*)}, 1, Tuple{Base.OneTo{Int64}}}, Matrix{Float64}, 1, Tuple{FillArrays.Fill{Matrix{Float64}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.Fields.GenericField{Main.PLaplacianTestsSeq.PLaplacianTests.var"#f#5"{Main.PLaplacianTestsSeq.PLaplacianTests.var"#σ#3", Main.PLaplacianTestsSeq.PLaplacianTests.var"#u#2"{Int64}}}, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, Vector{Float64}, 1, Tuple{Gridap.Arrays.LazyArray{Gridap.Geometry.CartesianMap{2, Float64, 4}, Vector{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{FillArrays.Fill{Vector{Gridap.TensorValues.VectorValue{2, Float64}}, 1, Tuple{Base.OneTo{Int64}}}}}}}}}}}, FillArrays.Fill{Vector{Float64}, 1, Tuple{Base.OneTo{Int64}}}, FillArrays.Fill{Vector{Gridap.TensorValues.TensorValue{2, 2, Float64, 4}}, 1, Tuple{Base.OneTo{Int64}}}}}}}, cell_rows::Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.FESpaces.AssemblyStrategyMap{:rows, Gridap.FESpaces.GenericAssemblyStrategy{typeof(identity), typeof(identity), GridapDistributed.var"#163#165"{Vector{Int32}}, GridapDistributed.var"#164#166"}}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Int64}, 1, Tuple{Gridap.Arrays.Table{Int32, Vector{Int32}, Vector{Int32}}}}, cell_cols::Gridap.Arrays.LazyArray{FillArrays.Fill{Gridap.FESpaces.AssemblyStrategyMap{:cols, Gridap.FESpaces.GenericAssemblyStrategy{typeof(identity), typeof(identity), GridapDistributed.var"#163#165"{Vector{Int32}}, GridapDistributed.var"#164#166"}}, 1, Tuple{Base.OneTo{Int64}}}, Vector{Int64}, 1, Tuple{Gridap.Arrays.Table{Int32, Vector{Int32}, Vector{Int32}}}})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/3bh1p/src/FESpaces/SparseMatrixAssemblers.jl:365
 [12] numeric_loop_matrix_and_vector!(A::PartitionedArrays.LocalView{Float64, 2, SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, Tuple{Vector{Int32}, Vector{Int32}}}, b::PartitionedArrays.LocalView{Float64, 1, Vector{Float64}, Tuple{Vector{Int32}}}, a::Gridap.FESpaces.GenericSparseMatrixAssembler, data::Tuple{Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}}})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/3bh1p/src/FESpaces/SparseMatrixAssemblers.jl:349
 [13] #4
    @ ./generator.jl:36 [inlined]
 [14] iterate
    @ ./generator.jl:47 [inlined]
 [15] collect(itr::Base.Generator{Base.Iterators.Zip{Tuple{Matrix{PartitionedArrays.LocalView{Float64, 2, SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, Tuple{Vector{Int32}, Vector{Int32}}}}, Matrix{PartitionedArrays.LocalView{Float64, 1, Vector{Float64}, Tuple{Vector{Int32}}}}, Matrix{Gridap.FESpaces.GenericSparseMatrixAssembler}, Matrix{Tuple{Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}}}}}}, Base.var"#4#5"{typeof(Gridap.FESpaces.numeric_loop_matrix_and_vector!)}})
    @ Base ./array.jl:681
 [16] map
    @ ./abstractarray.jl:2383 [inlined]
 [17] map_parts
    @ ~/.julia/packages/PartitionedArrays/0zLYD/src/SequentialBackend.jl:56 [inlined]
 [18] numeric_loop_matrix_and_vector!(A::PartitionedArrays.PSparseMatrix{Float64, PartitionedArrays.SequentialData{SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, 2}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}}, b::PartitionedArrays.PVector{Float64, PartitionedArrays.SequentialData{Vector{Float64}, 2}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}}, a::GridapDistributed.DistributedSparseMatrixAssembler{GridapDistributed.FullyAssembledRows, PartitionedArrays.SequentialData{Gridap.FESpaces.GenericSparseMatrixAssembler, 2}, GridapDistributed.PSparseMatrixBuilderCOO{SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, GridapDistributed.FullyAssembledRows}, GridapDistributed.PVectorBuilder{Vector{Float64}, GridapDistributed.FullyAssembledRows}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexSet, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexSet, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}}, data::PartitionedArrays.SequentialData{Tuple{Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}}}, 2})
    @ GridapDistributed ~/git-repos/GridapDistributed.jl/src/FESpaces.jl:406
 [19] assemble_matrix_and_vector_add!
    @ ~/.julia/packages/Gridap/3bh1p/src/FESpaces/SparseMatrixAssemblers.jl:128 [inlined]
 [20] assemble_matrix_and_vector!(A::PartitionedArrays.PSparseMatrix{Float64, PartitionedArrays.SequentialData{SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, 2}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}}, b::PartitionedArrays.PVector{Float64, PartitionedArrays.SequentialData{Vector{Float64}, 2}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}}, a::GridapDistributed.DistributedSparseMatrixAssembler{GridapDistributed.FullyAssembledRows, PartitionedArrays.SequentialData{Gridap.FESpaces.GenericSparseMatrixAssembler, 2}, GridapDistributed.PSparseMatrixBuilderCOO{SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, GridapDistributed.FullyAssembledRows}, GridapDistributed.PVectorBuilder{Vector{Float64}, GridapDistributed.FullyAssembledRows}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexSet, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexSet, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}}, data::PartitionedArrays.SequentialData{Tuple{Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}, Vector{Any}}, Tuple{Vector{Any}, Vector{Any}}}, 2})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/3bh1p/src/FESpaces/SparseMatrixAssemblers.jl:124
 [21] residual_and_jacobian!(b::PartitionedArrays.PVector{Float64, PartitionedArrays.SequentialData{Vector{Float64}, 2}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}}, A::PartitionedArrays.PSparseMatrix{Float64, PartitionedArrays.SequentialData{SparseMatricesCSR.SparseMatrixCSR{0, Float64, Int64}, 2}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexRange, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}}, op::Gridap.FESpaces.FEOperatorFromWeakForm, uh::GridapDistributed.DistributedCellField{PartitionedArrays.SequentialData{Gridap.FESpaces.SingleFieldFEFunction{Gridap.CellData.GenericCellField{Gridap.CellData.ReferenceDomain}}, 2}, GridapDistributed.DistributedFEFunctionData{PartitionedArrays.PVector{Float64, PartitionedArrays.SequentialData{Vector{Float64}, 2}, PartitionedArrays.PRange{PartitionedArrays.SequentialData{PartitionedArrays.IndexSet, 2}, PartitionedArrays.Exchanger{PartitionedArrays.SequentialData{Vector{Int32}, 2}, PartitionedArrays.SequentialData{PartitionedArrays.Table{Int32}, 2}}, Nothing}}}})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/3bh1p/src/FESpaces/FEOperatorsFromWeakForm.jl:91
 [22] main(parts::PartitionedArrays.SequentialData{Int64, 2}, strategy::GridapDistributed.FullyAssembledRows, local_matrix_type::Type)
    @ Main.PLaplacianTestsSeq.PLaplacianTests ~/git-repos/GridapDistributed.jl/test/PLaplacianTests.jl:45
 [23] main(parts::PartitionedArrays.SequentialData{Int64, 2})
    @ Main.PLaplacianTestsSeq.PLaplacianTests ~/git-repos/GridapDistributed.jl/test/PLaplacianTests.jl:11
 [24] prun(driver::typeof(Main.PLaplacianTestsSeq.PLaplacianTests.main), b::PartitionedArrays.SequentialBackend, nparts::Tuple{Int64, Int64})
    @ PartitionedArrays ~/.julia/packages/PartitionedArrays/0zLYD/src/Interfaces.jl:35
 [25] top-level scope
    @ ~/git-repos/GridapDistributed.jl/test/sequential/PLaplacianTests.jl:4
in expression starting at /home/amartin/git-repos/GridapDistributed.jl/test/sequential/PLaplacianTests.jl:1
```

**Comment by fverdugo** [comment]
We need to define `setindex!` for this matrix type.

**Comment by amartinhuertas** [comment]
> We need to define setindex! for this matrix type.

Ok, this is what I though. I will implement it.

**Comment by amartinhuertas** [comment]
> Ok, this is what I though. I will implement it.

I have implemented this in https://github.com/gridap/SparseMatricesCSR.jl/pull/18

However, note this could have been avoided if we declared `SparseLocalView` (new data type in PartitionedArrays.jl) as a subtype of `AbstractSparseMatrix` (instead of using `LocalView`, that is a subtype of `AbstractArray`).

In such a case, we would be leveraging the following in Gridap.jl:

```
function add_entry!(combine::Function,A::AbstractSparseMatrix,v::Number,i,j)
  k = nz_index(A,i,j)
  nz = nonzeros(A)
  Aij = nz[k]
  nz[k] = combine(v,Aij)
  A
end
``` 

instead of 

```
@inline function add_entry!(combine::Function,A::AbstractMatrix,v,i,j)
  aij = A[i,j]
  A[i,j] = combine(aij,v)
  A
end
```
Anyway, I think it makes sense to write `setindex!` for SparseMatrixCSR (it can be useful in other scenarios as well).

**Comment by amartinhuertas** [comment]
ok, tests are now passing. Ready to review.

**Pull request merged**
