### PR TITLE
Rhs assembly alone

### PR DESCRIPTION
**Pull request by amartinhuertas**
Hi @fverdugo, 

In this PR, I came up with an aproach to implement the rhs assembly for `SubAssembledRows()`, which is the complicated case. Let us decide if this is the way to go, possible improvements, etc.. The PR also solves the rhs assembly for the  `FullyAssembledRows()` strategy, although I would say there is not much to discuss here, this strategy is trivial.

The main difficulty comes from the fact that `SubAssembledRows()` requires the `lid`s of the ghost dofs which are touched during the assembly loop over owned cells. In the `matrix_and_vector_assemble` case, we are somehow cheating, because this information comes from the matrix assembly process, namely in the row identifiers array `I`.  The `PvectorBuilder`/`PVectorCounter`/`PVectorAllocation` set of assemble interface implementations alone do not seem to serve the purpose of providing this information (see [here](https://github.com/gridap/GridapDistributed.jl/blob/f8e383da956764f2adfa683e9d5b128d05c2d9eb/src/Algebra.jl#L370)).

What I did to overcome this limitation is (perhaps there are other cleaner options within the current software design constraints, I am open to reconsideration):
1. I implemented a symbolic assembly loop to track the ghost dofs touched from owned cells. This required me to overwrite the current implementation of the symbolic assemly loop in Gridap.  See [here](https://github.com/gridap/GridapDistributed.jl/blob/f8e383da956764f2adfa683e9d5b128d05c2d9eb/src/Algebra.jl#L509). If we agree this is the way to go, this code should be moved to Gridap.
2. The symbolic assembly loop is leveraged with a new set of types to implement the assemble interface abstractions. Namely, the `ArrayCounterSubAssembledRows{T,A}` type for the Gridap assembler, and the counterparts of the `PvectorBuilder`/`PVectorCounter`/`PVectorAllocation` types for the GridapDistributed assembler.
3. In order to leverage the data types implemented in 2., I had to intercept (overrride) the `assemble_vector` function in Gridap for the particular case in which we have the `SubAssembledRows` strategy. Besides, I cannot leverage the input `DistributedAssembler` for the symbolic stage, as it was by default initialized with the  `PvectorBuilder` type, which does not serve the purpose. As a result, I have to create an-hoc `DistributedAssembler` for the symbolic stage.This is arguibly the most controversial part of the PR.  See [here](https://github.com/gridap/GridapDistributed.jl/blob/ce94cf5f1a9da6a1c39e6368413ab0169373f9bc/src/FESpaces.jl#L447). 

I am far from 100% sure, but I have the impression that having the `MatrixBuilder`, `VectorBuilder`, and `AssemblyStrategy` instances tighted to the `Assembler`, and a unique `Assembler` in the program is somehow jeopardizing the flexibility of the current sofware design. To be general, one might want to select different assembly strategies to assemble the vector in  `assemble_matrix_vector` and `assemble_vector`.  Does it make sense to have `SparseMatrixAssembler` and `ArrayAssembler` separately? Anyway this is not the only issue in this particular scenario, as I needed to use different assembly strategies in the symbolic and numerical loop.

### CODE REVIEW

**Comment by amartinhuertas** [comment]
> Ok. I just realized that this is just an optimization. We could leverage the same assembly strategy for the symbolic and numeric loops, at the price of touching both owned and ghost dofs during the assembly loop over the owned cells. The need for different DistributedAssemblers persists.

Done in https://github.com/gridap/GridapDistributed.jl/pull/40/commits/ce94cf5f1a9da6a1c39e6368413ab0169373f9bc

**Review by fverdugo — CHANGES_REQUESTED** [review]
See my comments above

**Review by fverdugo — CHANGES_REQUESTED** [review]

**Review by fverdugo — CHANGES_REQUESTED** [review]
Se extra comments

**Comment by fverdugo** [comment]
> It seems that the assembly loop uses the local dof ids stored in FE space. It seems these produce out of bounds error when used to address the PVector without ghost dofs. Before I start debugging to understand the problem in detail, any hint? Might this be related with the issues in assemble_xxx! functions?

Yes, this is the problem and it's the cause of the issues in assemble_xxx! functions.

I already have a fix in my local machine and assemble_xxx! are working

**Comment by fverdugo** [comment]
perhaps we can put this PR in stand-by til I get the nonlinear problem working (since I am fixing a lot of issues in this process)

**Comment by amartinhuertas** [comment]
> I had to get the symbolic_loop_vector! back from a previous commit. We need it for allocate_vector. If we agree this is needed, then we should move this code to Gridap.

Done in https://github.com/gridap/Gridap.jl/pull/681

**Review by fverdugo — APPROVED** [review]

**Pull request merged**
