### PR TITLE
Adding sysimage generation to mpi tests

### PR DESCRIPTION
**Pull request by amartinhuertas**
Solve Medium Priority Task in #39

**IMPORTANT NOTE**: This PR MUST BE reviewed after https://github.com/gridap/GridapDistributed.jl/pull/47

### CODE REVIEW

**Review by fverdugo — CHANGES_REQUESTED** [review]
I am not sure about this. Introduces considerable complexity and it has not a positive impact in the test times. In fact, by looking the gh actions it seems to even lead to slower times.

Perhaps separating the sequential and mpi tests is enough for now.

**Comment by amartinhuertas** [comment]
> I am not sure about this. Introduces considerable complexity and it has not a positive impact in the test times. In fact, by looking the gh actions it seems to even lead to slower times.

Besides, we will be evaluating the ability to precompile GridapDistributed.jl. Such action for clusters is a must.

**Comment by amartinhuertas** [comment]
I think it makes a lot of sense to test the workflow that you are going to face when dealing with a cluster. The repo of apps is going to be abandoned, and not tested frequently (we have already many other experiences of similar repos).

**Comment by fverdugo** [comment]
and BTW the precompilation scrips should be in the "test app" (i.e. the final app) as usual

**Comment by amartinhuertas** [comment]
@fverdugo ... all tests are now passing. PR ready to review/merge.

The CI script generates the `TestApp.so` sysimage, and then leverages it to run the MPI tests with 1x and 4x MPI tasks.  The generation of the image takes 21 min according to github CI. On the other hand, the parallel MPI tests runtime is missleading in Gitlub CI: https://github.com/gridap/GridapDistributed.jl/runs/3970159570?check_suite_focus=true I think it only measures the time spent in the `runtests.jl` script, not the time spent in the mpirun processes forked out of it.

**Review by fverdugo — APPROVED** [review]

**Pull request merged**
