### PR TITLE
Transient distributed cell field

### PR DESCRIPTION
**Pull request by oriolcg**
Hi @santiagobadia, @amartinhuertas, @fverdugo, 

This is a draft PR that migrates the developments done in `GridapODEs` to support `GridapDistributed` into `GridapDistributed`. This is something that we discussed with @santiagobadia in the Slack channel. Please, take a look at the modifications and let me know what do you think.

The current status already works for the transient Poisson (heat equation) and Stokes equation, provided that `GridapODEs` is linked to the branch `support_GridapDistributed`

### CODE REVIEW

**Review by fverdugo — CHANGES_REQUESTED** [review]
Have you considered to add this work to GridapODEs and include GridapDistributed in the dependencies of GridapODEs?

This is the patter we have followed with the other packages. Eg. GridapGmsh and GridapPETSc depend on GridapDistributed, not viceversa.

**Comment by oriolcg** [comment]
> Have you considered to add this work to GridapODEs and include GridapDistributed in the dependencies of GridapODEs?

Yes, this is what I had already working in 3718467c399bda379329ee2d99bbeafec8a240dd. This migration came after a discussion with @santiagobadia (see the "#gridap-odes" channel in Slack).

**Comment by fverdugo** [comment]
I think it is significantly better that the extension packages depend on GridapDistributed, as we are doing now.

Otherwise, GridapDistributed would grow indefinitely large since it would potentially incorporate parallel code of all extension packages. As a result, the size of GridapDistribtued would be proportional to the number of extension packages, which does not scale clearly.

Moreover, I think it is also conceptually better to have everything related with gmsh in GridapGmsh (idepedentendly if it is serial or parallel code, this is just a detail), everything related with petsc in GridapPETSc, everything related with ODEs in GridapODEs etc.

**Comment by santiagobadia** [comment]
@fverdugo 

Gridap is a serial package and GridapDistributed is the layer that provides distributed-memory parallelism.The FE part is in Gridap and the parallel FE part is in GridapDistributed now. If this is the pattern for the spatial discretisation, I don't see why not for the time discretisation. For me, this is the consistent way to go.

GridapP4est, GridapGmsh, GridapPETSc are different packages, which are already parallelism-aware. In fact, they provide functionalities to GridapDistributed, not the other way around.

A user that wants to run in serial (most common case) is going to use Gridap / GridapODEs and no dependency with GridapDistributed is required. If this user now wants to make the driver parallel, they are going to add GridapDistributed. I think this is a clean and consistent way to go. Only when one wants to go to parallel, MPI, OpenMP, P4est, PETSc [...] will be downloaded.

But far more important, we don't want to add parallel tests to GridapODEs. It is much better to have the parallel tests in GridapDistributed. We know that including parallel tests is challenging, we have already suffered this in GridapDistributed. It makes no sense to suffer this in such a light package as GridapODEs (sysimage, precompilation, etc).

GridapDistributed is already a very light package, 2500 LOC. Adding a bunch of lines for GridapODEs is not a problem at all.

So, I propose to go the way used in this PR.

A deeper discussion that we can postpone (even though somehow related) is to create vs not to create new _discretisation_ packages (add the functionality to Gridap in a new submodule). It is quite subjective. E.g., why DG methods are in Gridap and hybridised methods are in GridapHybrid? We probably want to start thinking about merging some _curated_ packages. I don't have a strong opinion here. But using the approach suggested, it would be easier in the future, if needed. There are pros and cons.

**Comment by amartinhuertas** [comment]
In my view, it is reasonable to put the parallelization of GridapODEs in GridapDistributed, as in this PR. (putting it in GridapODEs is reasonable as well, but I believe that it adds some burdens to the user/developer of GridapODEs that leans the scale on the approach in this PR).

If GridapODEs was a part of Gridap (this would also be reasonable, as @santiagobadia  mentions), there would not be discussion, right?. Thus, I also believe this PR is the consistent way to go with the Gridap-GridapDistributed relation. As a bonus, you dont complicate the workflow, github actions, etc. of a package that was originally though to be a serial package. 

On the other hand, we have reduced GridapDistributed to the minimum. It is essentially a wrapper that combines different building blocks. While we are adding more LOCs of code to support GridapODEs parallelization (concern of @fverdugo), the code that we are adding it is in nature equivalent to the one that we already have in GridapDistributed for spatial discretization (wrapper types, combining building blocks, etc.) , thus this seems to be consistent as well. 

Finally, note that from the perspective of a user that wants to implement a parallel transient solver, there is essentially no difference among one decision or the other.

**Comment by amartinhuertas** [comment]
Something that we can always do is to put the parallelization code of GridapODEs into its own module of GridapDistributed, instead of in the main trunk. Just an idea, still thinking ....

**Comment by amartinhuertas** [comment]
> Something that we can always do is to put the parallelization code of GridapODEs into its own module of GridapDistributed, instead of in the main trunk. Just an idea, still thinking ....

I mean to have a submodule within GridapDistributed, called GridapODEs, and put all the code in this PR in GridapDistributed.GridapODEs. Note we do not have yet module hierarchy in GridapDistributed.

**Comment by santiagobadia** [comment]
Sure! I think it makes sense. And the same for tests. This way it is easy to cut.

@oriolcg you could create this submodule in the same PR.

Btw, the tests are not passing yet.

**Comment by oriolcg** [comment]
Ok, I'll create a submodule for this. 

> Btw, the tests are not passing yet.

The test are not passing because the CI does not link with the branch where I have the corresponding changes in `GridapODEs`. After merging and registering a new version they should work.

**Comment by fverdugo** [comment]
> GridapODEs was a part of Gridap there would not be discussion, right?

But it's not. To be consistent with this, I believe that all things that are related with GridapODEs should be in GridapODEs. Otherwise, we are breaking the modularity of the ecosystem in GridapDistributed.

As pointed @santiagobadia, the actual discussion is which packages should be in Gridap and which ones are extension packages. But if some functionality happens to not be merged in Gridap, please do not merge it in GridapDistributed.

**Comment by oriolcg** [comment]
`GridapODEs` submodule created in d1bfa5e228260f32ed26400d1f6a6b4880022cca. The tests should be passing once gridap/GridapODEs.jl#68 is released.

**Comment by oriolcg** [comment]
Hi @santiagobadia, @amartinhuertas, @fverdugo. How should we proceed with that? I would like to unlock this development soon. Would it work to have a dedicated meeting to go over pros-cons or possible alternatives?

**Comment by santiagobadia** [comment]
@oriolcg 

I have merged GridapODEs into Gridap. Can you update to 0.17.9?

After this, please, eliminate the GridapODEs dependency in Project.toml and modify `using GridapODEs...` by `using Gridap.GridapODEs...`.

Then, we can accept the PR

**Comment by oriolcg** [comment]
Done in d98f459b212b3ca8040263b1235d1245a3c1f6fc. The tests should pass after releasing PR gridap/Gridap.jl#751 and PR fverdugo/partitionedarrays.jl#74.

**Comment by oriolcg** [comment]
The tests are passing with the last Gridap release.

@fverdugo suggested to not add a submodule for ODEs, but probably this can be done in another PR.

**Comment by oriolcg** [comment]
Hi @amartinhuertas @fverdugo @santiagobadia, can this PR be accepted?

**Comment by fverdugo** [comment]
As a minor remark, I would remove the module ODEs to follow the same pattern as in the other parts of the code. E.g., there is no module MultiField in GridapDistributed. For the rest, OK.

**Comment by oriolcg** [comment]
> As a minor remark, I would remove the module ODEs to follow the same pattern as in the other parts of the code. E.g., there is no module MultiField in GridapDistributed. For the rest, OK.

Done in https://github.com/gridap/GridapDistributed.jl/pull/81/commits/5166991a5b4041bb54e5fedf8344a3fd7bd8325d

**Review by fverdugo — APPROVED** [review]

**Pull request merged**
