### PR TITLE
Bug-fix generate gids FE space

### PR DESCRIPTION
**Pull request by amartinhuertas**
Hi @fverdugo, 

I am pretty sure that the current algorithm for the generation of FE space global DoFs in a parallel distributed context is NOT correct (I am puzzled why it has worked in the vast majority of cases, possibly due to the fact the the bug is in the ghost cells). In particular, two sweeps of communication among nearest neighbours are required to have all correct global DoFs (including those which are solely on ghost cells), while the current algorithm only performs a single sweep. The figures below illustrate the situation 
IMG20211209105433
IMG20211209105455
IMG20211209105503

Besides, to have the full correct information about dof ownership, an extra comm sweep is needed for `ldof_to_part`.  What I did in this PR is to replicate  the algorithm that we had in GridapDistributed 0.1.0 (https://github.com/gridap/GridapDistributed.jl/blob/v0.1.0/src/DistributedFESpaces.jl#L107), which I am pretty sure it was correct.

### CODE REVIEW

**Comment by fverdugo** [comment]
Does this fix our stochastic bug? 🙏🏻🙏🏻

**Comment by amartinhuertas** [comment]
> Does this fix our stochastic bug? 🙏🏻🙏🏻

I am not 100% sure, but there are high changes that this is the case. The global gids that were causing dict key errors where unitialized gids on ghost cells.

**Comment by amartinhuertas** [comment]
Un-initialized arrays are the source of stochastic errors

**Comment by amartinhuertas** [comment]
Ok. `WeakDivPerpTests.jl` are now passing in `GridapGeosciences.jl` https://github.com/gridapapps/GridapGeosciences.jl/runs/4466930304?check_suite_focus=true#step:9:862

They were not before this bug.

**Review by fverdugo — APPROVED** [review]
@amartinhuertas I have no time to careful review this until second half of December. I guess that the fix is OK. Approving without reviewing 😁

**Comment by fverdugo** [comment]
Feel free to merge

**Comment by amartinhuertas** [comment]
> Feel free to merge

Ok, thanks. No worries! I can also take charge of reviewing from time to time. I will also answer Connor in regards to the AD issue on subdomains.

**Pull request merged**
